version: '3.7'
services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5434:5432
    # volumes:
    # - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
