GET http://localhost:3030/questions

###
OPTIONS http://localhost:3030/questions
Access-Control-Request-Method: PUT  
Access-Control-Request-Headers: content-type
Origin: https://not-origin.io

###
POST http://localhost:3030/questions
Content-Type: application/json

{
    "id":"4",
    "title":"New questions",
    "content": "question 3"
}

###
PUT http://localhost:3030/questions
Content-Type: application/json

{   
    "id": "A",
   
    "content": "question 2"
}

###

POST https://api.apilayer.com/bad_words?censor_character=* 

"shitty-length"

###

POST http://localhost:3030/questions HTTP/1.1
Content-Type:application/json

{
    "title" : "New Ass Title",
    "content": "OLD Content shit"
}